# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-06 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodspot', '0002_foodspot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='landmark',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
