# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-11 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodspot', '0003_auto_20171206_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodspot',
            name='image',
            field=models.ImageField(max_length=1000, null=True, upload_to='foodspots/'),
        ),
    ]
