# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-24 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodspot', '0004_foodspot_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodSpotImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='foodspots')),
            ],
        ),
        migrations.RemoveField(
            model_name='foodspot',
            name='image',
        ),
        migrations.AddField(
            model_name='foodspot',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='foodspot',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='foodspot',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodspotimage',
            name='foodSpot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='foodspot.FoodSpot'),
        ),
    ]
