# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-25 18:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodspot', '0005_auto_20171224_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodspot',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 25, 18, 18, 45, 975328), editable=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(default='Warangal', max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='pincode',
            field=models.CharField(default=506004, max_length=10),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(default='Telangana', max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='streetAddress',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
