# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-25 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodspot', '0006_auto_20171225_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='foodspot',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='foodspotimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
