# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-28 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodspot', '0010_foodspot_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credits',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
