# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-28 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodspot', '0013_foodspotcomment_foodspotvote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodspotcomment',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='foodspotvote',
            old_name='user',
            new_name='owner',
        ),
    ]
